name: Snapcash Collection with Environment

on:
  push:
    branches:
      - main  
jobs:
  run-postman-collection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  

    - name: Install Newman
      run: npm install -g newman

    - name: Snapcash Collection with Environment
      run: newman run "XSnapCash QA Test.postman_collection.json" -e "NewTest_Lendsqr_GW_postman_environment.json"
